# manifests/cloudrun-base.yaml
# This is the base blueprint for your Deno Cloud Run service.
# Skaffold profiles will apply changes on top of this.

apiVersion: serving.knative.dev/v1 # Standard API version for Cloud Run services
kind: Service # This defines a Cloud Run Service
metadata:
  # The 'name' will be overridden by Skaffold profiles for 'staging' and 'prod'.
  # You can put a default name here, or even a placeholder like 'my-deno-app-default'.
  # For clarity, let's put the staging name here as a base.
  name: zeyra-base # Default name for the service. Overridden by profiles.
spec:
  template:
    spec:
      containers:
        # Cloud Deploy/Skaffold injects the image tag here (e.g., commit SHA)
        - image: us-east1-docker.pkg.dev/zeyra-466314/my-deno-repo/deno-app:${TAG}
