services:
  dev:
    build:
      context: .
      target: dev
    develop:
      watch:
        - action: sync
          path: client
          target: /app/client
        - action: sync
          path: server
          target: /app/server
        - action: rebuild
          path: package.json
    ports:
      - 8080:8080
      - 24678:24678
